services:
  alist-rclone:
    image: ghcr.io/workerspages/alist-rclone:main
    container_name: alist-rclone
    restart: unless-stopped
    ports:
      - "5244:80"
    volumes:
      - ./data:/data
      - ./host:/opt/host:ro # 映射宿主机目录至容器内，用于本地与网盘间的文件传输
    environment:
      - TZ=Asia/Shanghai
      - SWAP_SIZE_MB=512
      # Web 控制台登录凭据
      - WEB_USERNAME=admin
      - WEB_PASSWORD=admin
      # Alist 管理员凭据
      - ALIST_ADMIN_USERNAME=admin
      - ALIST_ADMIN_PASSWORD=admin
